# Reusable workflow for building and pushing docker images to ECR
name: Build and Push images to ECR

on:
  workflow_call:
    outputs:
      ui-image:
        description: JSON object as string containing all tags of the built images
        value: ${{ jobs.build-and-push-image.outputs.ui-image }}

jobs:
  build-and-push-image:
    name: Build and push images to ECR
    runs-on: ubuntu-20.04
    outputs:
      ui-image: ${{ steps.output-tag.outputs.ui }}

    strategy:
      fail-fast: true
      matrix:
        include:
          - dockerfile: ./ui/Dockerfile
            context: ui
      # conditionally skip matrix https://github.com/orgs/community/discussions/26253#discussioncomment-3250989

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Define ECR registry
        id: registry
        run: echo "::set-output name=result::${{ steps.login-ecr-public.outputs.registry }}/u6u0a7r2/node-test"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Define tag
        id: define-tag

        # TODO apply pr title if exists
        run: |
          ATTEMPT=${{ github.run_attempt }}
          SHORT_SHA=$(git rev-parse --short HEAD)
          if [ "$ATTEMPT" -gt 1 ]; then SUFFIX="-$ATTEMPT"; else a=""; fi
          echo "::set-output name=result::${{ matrix.context }}-${SHORT_SHA}$SUFFIX"

      - name: Build and push image
        uses: docker/build-push-action@v3
        id: build-push
        with:
          push: true
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          tags: ${{ steps.registry.outputs.result }}:${{ steps.define-tag.outputs.result }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          # https://www.nicolabs.net/2021/Speed-up-automated-docker-build-with-github-actions

      - name: Output tag
        id: output-tag
        run: |
          TAG=${{ steps.registry.outputs.result }}:${{ steps.define-tag.outputs.result }}
          echo $TAG taggg
          echo "::set-output name=${{ matrix.context }}::$TAG"
