# Reusable workflow for creating a git tag bumping the semver and adding the
# ECR images inside this tag
name: Create git tag

on:
  workflow_call:
    inputs:
      semver-level:
        description: The semver level (major, minor, patch or prerelease). Use prerelease for hotfixes.
        required: true
        type: string
      # TODO docker images

    outputs:
      new-tag:
        description: The bumped tag
        value: ${{ jobs.git-tag.outputs.version }}

jobs:
  git-tag:
    name: Bump and create git tag
    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.bump-semver.outputs.new_version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - name: Find the latest tag in the same branch
        id: latest-tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "::set-output name=result::$LATEST_TAG"

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.latest-tag.outputs.result }}
          level: ${{ inputs.semver-level }}

      - name: Short SHA
        id: sha
        run: |
          echo $(git rev-parse --short HEAD)
          echo "::set-output name=short::$(git rev-parse --short HEAD)"

      - name: Tag the current commit in git
        uses: actions/github-script@v6
        with:
          script: |
            const bumped = "${{ steps.bump-semver.outputs.new_version }}";
            const shortSha = "${{ steps.sha.outputs.short }}";
            const attempt = ${{ github.run_attempt }};
            console.log(attempt === 1);

            const newTag = `${bumped}+${shortSha}`;
            console.log(`Previous tag: ${{ steps.latest-tag.outputs.result }}. New tag: ${newTag}`);

            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${newTag}`,
              sha: context.sha
            });
