name: Hotfix CI
on:
  push:
    branches:
      - hotfix*

jobs:
  build:
    name: Build and push images to ECR
    uses: ./.github/workflows/build-and-push-images.yml
    secrets: inherit

  git-tag:
    needs: build
    name: Tag commit in git
    uses: ./.github/workflows/git-tag.yml
    with:
      semver-level: prerelease
