name: Main CI
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push images to ECR
    uses: ./.github/workflows/build-and-push-images.yml
    secrets: inherit

  semver-level:
    needs: build
    name: Find the semver level
    runs-on: ubuntu-20.04
    outputs:
      level: ${{ steps.semver-level.outputs.result }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5

      - uses: actions/github-script@v6
        name: Find the semver level of the PR of the latest commit
        id: semver-level
        with:
          result-encoding: string
          script: |
            const script = require('./.github/workflows/scripts/semver-level-pr.js');
            return await script({github, context, core});

  git-tag:
    needs: semver-level
    name: Tag commit in git
    uses: ./.github/workflows/git-tag.yml
    with:
      semver-level: ${{ needs.semver-level.outputs.level }}
