name: Pull Request Workflow
on: pull_request

jobs:
  validate-pr:
    name: Validate Release Label
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: jefflinse/pr-semver-bump@v1
        name: Validate Pull Request Metadata
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
