name: Pull Request Workflow
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  validate-pr:
    name: Validate Release Label
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Validate Pull Request Metadata
        uses: jefflinse/pr-semver-bump@v1.3.2
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
