name: Pull Request Workflow
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  validate-pr:
    name: Validate Release Label
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload?.pull_request?.labels;
            console.log(labels);
            const releaseLabels = labels.filter(
              (l) => l === "release/major" || l === "release/minor" || l === "release/patch"
            );
            console.log("Release labels: ", releaseLabels);
            if (releaseLabels !== 1) core.setFailed('You must specify a release label level (major, minor or patch).');
