name: Pull Request Workflow
on:
  pull_request:
    types: [labeled, unlabeled, opened, reopened, synchronize]

jobs:
  validate-pr:
    name: Validate Release Label
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions-ecosystem/action-release-label@v1
        id: release-label

      - if: ${{ steps.release-label.outputs.level == null }}
        run: |
          "::error::You must specify a release level: major, minor or patch."
          exit 1
